import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Topology.Algebra.InfiniteSum.Basic
import Mathlib.Analysis.Analytic.Basic
import Mathlib.Analysis.Analytic.Uniqueness
import Mathlib.Analysis.Analytic.OfScalars
import Mathlib.Data.NNReal.Basic
import Mathlib.Data.ENNReal.Basic
import Ripple.Number.AperyConifoldIndicial

open scoped NNReal ENNReal

/-!
# Frobenius disk at a regular point

For the conifold ODE driving Apéry's sequence, the connection-coefficient
analysis in `AperyGeneratingFunction` is anchored at the singular point
`z₁ = 17 − 12√2` where the indicial roots are `{0, 1/2, 1}`. To extend
the analytic continuation beyond the small `[0, 1/64)` Frobenius disk
around `z₁`, we need a separate object representing the Frobenius
expansion at an arbitrary *regular* point of the ODE — where all three
indicial roots collapse to `0` and the local expansion is an ordinary
power series with no `√` or `log` prefactor.

This file introduces the minimal geometric structure
`AperyRegularDisk`: a center, a convergence radius, an analytic
function, a coefficient sequence, and the `HasSum` identity tying them
together. ODE compatibility constraints are added in subsequent files.

The eventual goal (gap B) is a chaining tool: starting from a point
inside the `z₁`-anchored Frobenius disk, build a sequence of overlapping
regular-point disks reaching points where `aperyGFAReal` (the GFA
`tsum`) is known, transferring the connection-coefficient identification
across the chain.
-/

namespace Ripple
namespace Frobenius

open Ripple.Number

/-- **Frobenius disk centered at a regular point of the conifold ODE.**
A geometric scaffold: an analytic function `F` represented by the power
series `∑ coeffs n · t^n` on the open disk `|t| < radius` around
`center`. ODE compatibility (that `F` satisfies the conifold ODE and
`coeffs` is generated by the standard recursion) is layered on top in
subsequent definitions. -/
structure AperyRegularDisk where
  /-- Expansion center (a regular point of the conifold ODE). -/
  center : ℝ
  /-- Convergence radius of the local power series. -/
  radius : ℝ
  /-- Strict positivity of the radius. -/
  radius_pos : 0 < radius
  /-- The analytic function whose local expansion is recorded. -/
  F : ℝ → ℝ
  /-- Power-series coefficients of `F` about `center`. -/
  coeffs : ℕ → ℝ
  /-- `F (center + t) = ∑ n, coeffs n · t^n` whenever `|t| < radius`. -/
  has_sum_in_disk : ∀ t : ℝ, |t| < radius →
    HasSum (fun n => coeffs n * t^n) (F (center + t))

namespace AperyRegularDisk

/-- **Evaluate `F` at a local offset.** -/
@[simp] def evalAt (d : AperyRegularDisk) (t : ℝ) : ℝ := d.F (d.center + t)

@[simp] lemma evalAt_zero (d : AperyRegularDisk) :
    d.evalAt 0 = d.F d.center := by simp [evalAt]

/-- **Coefficient at index 0 equals `F center`.** Specialization of the
`HasSum` identity at `t = 0`. -/
lemma coeffs_zero_eq_F_center (d : AperyRegularDisk) :
    d.coeffs 0 = d.F d.center := by
  have h0 : |(0 : ℝ)| < d.radius := by
    rw [abs_zero]; exact d.radius_pos
  have hsum := d.has_sum_in_disk 0 h0
  -- Rewrite the summand: `coeffs n * 0^n = if n = 0 then coeffs 0 else 0`.
  have hsing : HasSum (fun n : ℕ => d.coeffs n * (0 : ℝ) ^ n) (d.coeffs 0) := by
    have heq : (fun n : ℕ => d.coeffs n * (0 : ℝ) ^ n) =
        fun n : ℕ => if n = 0 then d.coeffs 0 else 0 := by
      funext n
      cases n with
      | zero => simp
      | succ k => simp
    rw [heq]
    exact hasSum_single 0 (fun n hn => if_neg hn)
  have := hsum.unique hsing
  simpa using this.symm

/-- **Open disk of definition.** The set of points `z` for which the
local power-series expansion of `F` about `center` converges. -/
def diskOpen (d : AperyRegularDisk) : Set ℝ :=
  {z | |z - d.center| < d.radius}

@[simp] lemma mem_diskOpen (d : AperyRegularDisk) (z : ℝ) :
    z ∈ d.diskOpen ↔ |z - d.center| < d.radius := Iff.rfl

lemma center_mem_diskOpen (d : AperyRegularDisk) :
    d.center ∈ d.diskOpen := by
  simp [diskOpen, d.radius_pos]

lemma diskOpen_isOpen (d : AperyRegularDisk) : IsOpen d.diskOpen := by
  unfold diskOpen
  exact isOpen_lt (by fun_prop) continuous_const

lemma diskOpen_eq_ball (d : AperyRegularDisk) :
    d.diskOpen = Metric.ball d.center d.radius := by
  ext z
  simp [diskOpen, Metric.mem_ball, Real.dist_eq]

lemma convex_diskOpen (d : AperyRegularDisk) : Convex ℝ d.diskOpen := by
  rw [diskOpen_eq_ball]
  exact convex_ball d.center d.radius

lemma diskOpen_isPreconnected (d : AperyRegularDisk) :
    IsPreconnected d.diskOpen :=
  (convex_diskOpen d).isPreconnected

/-- **Pairwise overlap of disks is preconnected.** Intersection of
two open disks (each convex in ℝ) remains convex, hence preconnected.
This discharges the `IsPreconnected` hypothesis of
`Compatible.of_eventuallyEq_of_preconnected_overlap` and the chain
lemmas without any user input. -/
lemma diskOpen_inter_isPreconnected (d₁ d₂ : AperyRegularDisk) :
    IsPreconnected (d₁.diskOpen ∩ d₂.diskOpen) :=
  ((convex_diskOpen d₁).inter (convex_diskOpen d₂)).isPreconnected

/-- **Pointwise representation of `F` on the open disk.** Restating
`has_sum_in_disk` in absolute coordinates: for every `z` in the open
disk, `F z` is the `HasSum` of `coeffs n · (z − center)^n`. -/
lemma has_sum_pointwise (d : AperyRegularDisk) {z : ℝ}
    (hz : z ∈ d.diskOpen) :
    HasSum (fun n => d.coeffs n * (z - d.center) ^ n) (d.F z) := by
  rw [mem_diskOpen] at hz
  have hsum := d.has_sum_in_disk (z - d.center) hz
  simpa [add_comm, sub_add_cancel] using hsum

/-- **`F` equals the local series sum at any point of the disk.** -/
lemma F_eq_tsum (d : AperyRegularDisk) {z : ℝ} (hz : z ∈ d.diskOpen) :
    d.F z = ∑' n, d.coeffs n * (z - d.center) ^ n :=
  (d.has_sum_pointwise hz).tsum_eq.symm

/-- **Radius lower bound for the formal `ofScalars` series.** Given
that the absolute series `Σ |coeffs n| · r'^n` converges for every
real `r' ∈ [0, d.radius)`, the radius of convergence of
`FormalMultilinearSeries.ofScalars ℝ d.coeffs` (in `ℝ≥0∞`) is at
least `ENNReal.ofReal d.radius`.

Used to discharge the `r_le` field of `HasFPowerSeriesOnBall` when
packaging an `AperyRegularDisk` as a Mathlib power-series ball. -/
lemma le_radius_ofScalars (d : AperyRegularDisk)
    (hSum : ∀ r' : ℝ≥0, (r' : ℝ) < d.radius →
      Summable (fun n : ℕ => |d.coeffs n| * (r' : ℝ) ^ n)) :
    ENNReal.ofReal d.radius ≤
      (FormalMultilinearSeries.ofScalars ℝ d.coeffs).radius := by
  set p : FormalMultilinearSeries ℝ ℝ ℝ :=
    FormalMultilinearSeries.ofScalars ℝ d.coeffs with hp_def
  refine le_of_forall_lt_imp_le_of_dense fun x hx => ?_
  have hx_top : x ≠ ⊤ := ne_top_of_lt (lt_of_lt_of_le hx le_top)
  set s : ℝ≥0 := x.toReal.toNNReal with hs_def
  have hs_nn : 0 ≤ x.toReal := ENNReal.toReal_nonneg
  have hcoe_real : (s : ℝ) = x.toReal := Real.coe_toNNReal _ hs_nn
  have hcoe_ennreal : (s : ℝ≥0∞) = x := by
    rw [ENNReal.coe_nnreal_eq, hcoe_real]; exact ENNReal.ofReal_toReal hx_top
  have hs_lt : (s : ℝ) < d.radius := by
    rw [hcoe_real]
    have hxlt : x < ENNReal.ofReal d.radius := hx
    rw [← ENNReal.ofReal_toReal hx_top] at hxlt
    exact (ENNReal.ofReal_lt_ofReal_iff_of_nonneg hs_nn).mp hxlt
  have hsum := hSum s hs_lt
  have hsum' : Summable (fun n => ‖p n‖ * (s : ℝ) ^ n) := by
    convert hsum using 1
    funext n
    rw [hp_def, FormalMultilinearSeries.ofScalars_norm, Real.norm_eq_abs]
  have hr_le : (s : ℝ≥0∞) ≤ p.radius := p.le_radius_of_summable_norm hsum'
  rw [hcoe_ennreal] at hr_le
  exact hr_le

/-- **`HasSum` for the formal `ofScalars` series.** Reformulation of
`has_sum_in_disk` in the form required by Mathlib's
`HasFPowerSeriesOnBall.hasSum` field: at any `y` inside the
`ENNReal.ofReal d.radius`-eball around `0`, the term-by-term
evaluation of `FormalMultilinearSeries.ofScalars ℝ d.coeffs` at the
constant tuple `fun _ ↦ y` sums to `d.F (d.center + y)`. -/
lemma hasSum_ofScalars (d : AperyRegularDisk) {y : ℝ}
    (hy : y ∈ Metric.eball (0 : ℝ) (ENNReal.ofReal d.radius)) :
    HasSum
      (fun n : ℕ => FormalMultilinearSeries.ofScalars ℝ d.coeffs n (fun _ => y))
      (d.F (d.center + y)) := by
  rw [Metric.eball_ofReal] at hy
  have hy' : |y| < d.radius := by
    rw [Metric.mem_ball, Real.dist_eq, sub_zero] at hy
    exact hy
  have hsum := d.has_sum_in_disk y hy'
  convert hsum using 1
  funext n
  rw [FormalMultilinearSeries.ofScalars_apply_eq, smul_eq_mul]

/-! ### Compatibility and overlap

Two regular disks are *compatible* if their analytic functions agree on
the geometric intersection of their domains. This is the chaining
foundation: forward analytic continuation is built by patching together
overlapping compatible disks. -/

/-- **Two disks are compatible if their `F` values agree on the
geometric overlap.** -/
def Compatible (d₁ d₂ : AperyRegularDisk) : Prop :=
  ∀ z, z ∈ d₁.diskOpen → z ∈ d₂.diskOpen → d₁.F z = d₂.F z

@[refl] lemma Compatible.refl (d : AperyRegularDisk) : Compatible d d :=
  fun _ _ _ => rfl

@[symm] lemma Compatible.symm {d₁ d₂ : AperyRegularDisk}
    (h : Compatible d₁ d₂) : Compatible d₂ d₁ :=
  fun z hz₂ hz₁ => (h z hz₁ hz₂).symm

/-- **Compatible disks agree at every overlap point.** Direct
restatement; the existence of any common point implies a value
identity. -/
lemma Compatible.F_eq {d₁ d₂ : AperyRegularDisk} (h : Compatible d₁ d₂)
    {z : ℝ} (hz₁ : z ∈ d₁.diskOpen) (hz₂ : z ∈ d₂.diskOpen) :
    d₁.F z = d₂.F z := h z hz₁ hz₂

/-- **Compatible disks share local series sums at overlap points.** Both
local representations evaluate to the same function value, so the
absolute power series of `d₁` at `z` and the absolute power series of
`d₂` at `z` have a common limit. -/
lemma Compatible.tsum_eq {d₁ d₂ : AperyRegularDisk}
    (h : Compatible d₁ d₂) {z : ℝ}
    (hz₁ : z ∈ d₁.diskOpen) (hz₂ : z ∈ d₂.diskOpen) :
    ∑' n, d₁.coeffs n * (z - d₁.center) ^ n =
      ∑' n, d₂.coeffs n * (z - d₂.center) ^ n := by
  rw [← d₁.F_eq_tsum hz₁, ← d₂.F_eq_tsum hz₂]
  exact h.F_eq hz₁ hz₂

/-- **Trivial sufficient condition: shared `F`.** Two disks with the
same underlying analytic function are compatible. -/
lemma Compatible.of_F_eq {d₁ d₂ : AperyRegularDisk} (hF : d₁.F = d₂.F) :
    Compatible d₁ d₂ := fun z _ _ => by rw [hF]

/-- **Pointwise three-disk value transitivity.** If `d₁` is compatible
with `d₂` and `d₂` is compatible with `d₃`, then at any *common* triple
overlap point the values of `d₁.F` and `d₃.F` coincide — without
requiring `d₂.diskOpen` to cover `d₁.diskOpen ∩ d₃.diskOpen`. -/
lemma Compatible.F_eq_trans {d₁ d₂ d₃ : AperyRegularDisk}
    (h₁₂ : Compatible d₁ d₂) (h₂₃ : Compatible d₂ d₃) {z : ℝ}
    (hz₁ : z ∈ d₁.diskOpen) (hz₂ : z ∈ d₂.diskOpen) (hz₃ : z ∈ d₃.diskOpen) :
    d₁.F z = d₃.F z :=
  (h₁₂.F_eq hz₁ hz₂).trans (h₂₃.F_eq hz₂ hz₃)

/-- **Compatibility transitivity under a coverage hypothesis.** When
`d₂.diskOpen` contains the entire `d₁`-`d₃` overlap, compatibility
chains: `d₁ ~ d₂ ~ d₃ ⇒ d₁ ~ d₃`. -/
@[trans] lemma Compatible.trans {d₁ d₂ d₃ : AperyRegularDisk}
    (h₁₂ : Compatible d₁ d₂) (h₂₃ : Compatible d₂ d₃)
    (hsub : d₁.diskOpen ∩ d₃.diskOpen ⊆ d₂.diskOpen) :
    Compatible d₁ d₃ := by
  intro z hz₁ hz₃
  have hz₂ : z ∈ d₂.diskOpen := hsub ⟨hz₁, hz₃⟩
  exact h₁₂.F_eq_trans h₂₃ hz₁ hz₂ hz₃

/-- **Chained value equality through a common point.** Along a
finite sequence `ds 0, …, ds n` of disks with adjacent compatibility
and a single point `z` lying in every disk's open domain, the values
`(ds 0).F z` and `(ds n).F z` coincide. The pointwise common-point
hypothesis avoids the coverage assumption that the relational `trans`
needs. -/
lemma Compatible.F_eq_chain (ds : ℕ → AperyRegularDisk) (n : ℕ)
    (hcomp : ∀ i, i < n → Compatible (ds i) (ds (i + 1)))
    {z : ℝ} (hz : ∀ i, i ≤ n → z ∈ (ds i).diskOpen) :
    (ds 0).F z = (ds n).F z := by
  induction n with
  | zero => rfl
  | succ k ih =>
    have hcomp_prev : ∀ i, i < k → Compatible (ds i) (ds (i + 1)) :=
      fun i hi => hcomp i (Nat.lt_succ_of_lt hi)
    have hz_prev : ∀ i, i ≤ k → z ∈ (ds i).diskOpen :=
      fun i hi => hz i (Nat.le_succ_of_le hi)
    have hk_eq : (ds 0).F z = (ds k).F z := ih hcomp_prev hz_prev
    have hkk1 : Compatible (ds k) (ds (k + 1)) := hcomp k (Nat.lt_succ_self k)
    have hzk : z ∈ (ds k).diskOpen := hz k (Nat.le_succ k)
    have hzk1 : z ∈ (ds (k + 1)).diskOpen := hz (k + 1) (le_refl _)
    rw [hk_eq, hkk1.F_eq hzk hzk1]

end AperyRegularDisk

/-! ### Regular points of the conifold ODE

A point `z` is *regular* for the Apéry conifold ODE if the leading
polynomial `p(z) = z² − 34 z³ + z⁴` does not vanish there. At regular
points the Frobenius indicial polynomial degenerates to `ρ³ = 0`, so
all three indicial roots are `0` and the local Frobenius expansion is
an ordinary power series with no `√` or `log` prefactor — exactly the
shape carried by `AperyRegularDisk`. -/

/-- **Regular-point predicate.** The leading polynomial of the conifold
ODE is non-zero. -/
def AperyConifoldRegularPoint (z : ℝ) : Prop :=
  Polynomial.eval z Ripple.Number.aperyPconifold ≠ 0

/-- **Singular points of the conifold ODE are `{0, z₁, z̄₁}`.** The
leading polynomial factors as `z² (z² − 34 z + 1)`, so it vanishes
exactly at `z = 0` and the two roots of the quadratic. The two
non-zero roots are `z₁ = 17 − 12√2` and `z̄₁ = 17 + 12√2`. -/
lemma aperyPconifold_eval_eq (z : ℝ) :
    Polynomial.eval z Ripple.Number.aperyPconifold =
      z ^ 2 * (z ^ 2 - 34 * z + 1) := by
  unfold Ripple.Number.aperyPconifold
  rw [Polynomial.eval_add, Polynomial.eval_add, Polynomial.eval_monomial,
    Polynomial.eval_monomial, Polynomial.eval_monomial]
  ring

/-- **Regularity criterion via the factored form.** A point is regular
iff `z ≠ 0` and `z² − 34 z + 1 ≠ 0`. -/
lemma aperyConifoldRegularPoint_iff (z : ℝ) :
    AperyConifoldRegularPoint z ↔ z ≠ 0 ∧ z ^ 2 - 34 * z + 1 ≠ 0 := by
  unfold AperyConifoldRegularPoint
  rw [aperyPconifold_eval_eq]
  constructor
  · intro h
    refine ⟨?_, ?_⟩
    · intro hz0
      apply h
      rw [hz0]; ring
    · intro hquad
      apply h
      rw [hquad]; ring
  · rintro ⟨hz, hquad⟩ hprod
    rcases mul_eq_zero.mp hprod with h | h
    · exact hz (pow_eq_zero_iff (n := 2) (by norm_num) |>.mp h)
    · exact hquad h

/-- **`AperyRegularDisk` whose center is a regular point of the ODE.**
The minimal subtype recording the geometric prerequisite for an
ordinary-power-series Frobenius expansion. -/
structure AperyRegularDiskAt where
  /-- Underlying geometric scaffold. -/
  toAperyRegularDisk : AperyRegularDisk
  /-- The center is a regular point of the conifold ODE. -/
  regular : AperyConifoldRegularPoint toAperyRegularDisk.center

namespace AperyRegularDiskAt

/-- **Project to the underlying geometric disk.** -/
@[simp] def diskOpen (d : AperyRegularDiskAt) : Set ℝ :=
  d.toAperyRegularDisk.diskOpen

/-- **Project to the analytic function.** -/
@[simp] def F (d : AperyRegularDiskAt) : ℝ → ℝ := d.toAperyRegularDisk.F

/-- **Compatibility lifted from the underlying disks.** -/
def Compatible (d₁ d₂ : AperyRegularDiskAt) : Prop :=
  AperyRegularDisk.Compatible d₁.toAperyRegularDisk d₂.toAperyRegularDisk

@[refl] lemma Compatible.refl (d : AperyRegularDiskAt) : Compatible d d :=
  AperyRegularDisk.Compatible.refl _

@[symm] lemma Compatible.symm {d₁ d₂ : AperyRegularDiskAt} (h : Compatible d₁ d₂) :
    Compatible d₂ d₁ :=
  AperyRegularDisk.Compatible.symm h

lemma Compatible.F_eq {d₁ d₂ : AperyRegularDiskAt} (h : Compatible d₁ d₂)
    {z : ℝ} (hz₁ : z ∈ d₁.diskOpen) (hz₂ : z ∈ d₂.diskOpen) :
    d₁.F z = d₂.F z :=
  AperyRegularDisk.Compatible.F_eq h hz₁ hz₂

/-- **Chained value equality through a common point** (regular-center
version). -/
lemma Compatible.F_eq_chain (ds : ℕ → AperyRegularDiskAt) (n : ℕ)
    (hcomp : ∀ i, i < n → Compatible (ds i) (ds (i + 1)))
    {z : ℝ} (hz : ∀ i, i ≤ n → z ∈ (ds i).diskOpen) :
    (ds 0).F z = (ds n).F z :=
  AperyRegularDisk.Compatible.F_eq_chain
    (fun i => (ds i).toAperyRegularDisk) n hcomp hz

end AperyRegularDiskAt

/-! ### Regular-point coverage of the GFA convergence interval

The two non-zero singular roots are `17 ± 12√2`; the smaller is
`z₁ ≈ 0.0294` which already exceeds `1/64 ≈ 0.0156`. So every interior
point of the GFA convergence interval `(0, 1/64)` is regular. -/

/-- **Quadratic positivity on `(0, 1/64)`.** For `0 < z < 1/64`,
`z² − 34 z + 1 > 0`. -/
lemma aperyPconifoldQuad_pos_on_GFA_interval {z : ℝ} (hz_pos : 0 < z)
    (hz_lt : z < 1 / 64) :
    0 < z ^ 2 - 34 * z + 1 := by
  have hz_sq_nn : 0 ≤ z ^ 2 := sq_nonneg z
  nlinarith [hz_pos, hz_lt, hz_sq_nn]

/-- **GFA-interval interior points are regular.** Every `z ∈ (0, 1/64)`
is a regular point of the conifold ODE. -/
lemma aperyConifoldRegularPoint_of_GFA_interval {z : ℝ} (hz_pos : 0 < z)
    (hz_lt : z < 1 / 64) :
    AperyConifoldRegularPoint z := by
  rw [aperyConifoldRegularPoint_iff]
  refine ⟨ne_of_gt hz_pos, ?_⟩
  exact ne_of_gt (aperyPconifoldQuad_pos_on_GFA_interval hz_pos hz_lt)

/-! ### Analytic-on-disk upgrade

The geometric `AperyRegularDisk` only carries pointwise `HasSum` data;
to invoke Mathlib's identity theorem
(`AnalyticOnNhd.eqOn_of_preconnected_of_eventuallyEq`) and propagate
function-equality across overlapping disks, we need an analytic-
function field. `AperyAnalyticDisk` packages this. -/

/-- **Analytic regular disk.** A geometric `AperyRegularDisk` together
with a real-analyticity-on-neighborhood proof for its `F` on `diskOpen`.
The added field is the hypothesis Mathlib's identity theorem requires;
inhabitation (deriving `AnalyticOnNhd ℝ F diskOpen` from
`has_sum_in_disk`) is a standard but separate task. -/
structure AperyAnalyticDisk extends AperyRegularDisk where
  /-- `F` is real-analytic on a neighborhood of every point of the
  open disk. -/
  analytic : AnalyticOnNhd ℝ F toAperyRegularDisk.diskOpen

namespace AperyAnalyticDisk

/-- **Lift via a Mathlib power-series witness.** Given an
`AperyRegularDisk d` and a `HasFPowerSeriesOnBall` for `d.F` at
`d.center` with radius `ENNReal.ofReal d.radius`, package the result
as an `AperyAnalyticDisk`. The diskOpen↔eball rewriting is handled
internally via `diskOpen_eq_ball` and `Metric.eball_ofReal`. -/
def ofHasFPowerSeriesOnBall
    (d : AperyRegularDisk) (p : FormalMultilinearSeries ℝ ℝ ℝ)
    (hp : HasFPowerSeriesOnBall d.F p d.center (ENNReal.ofReal d.radius)) :
    AperyAnalyticDisk where
  toAperyRegularDisk := d
  analytic := by
    rw [d.diskOpen_eq_ball, ← Metric.eball_ofReal]
    exact hp.analyticOnNhd

/-- **Structure-level lift.** When the user already has the
`AnalyticOnNhd` proof, this is just the underlying constructor with
the data tidied up. -/
def ofAperyRegularDisk
    (d : AperyRegularDisk) (h : AnalyticOnNhd ℝ d.F d.diskOpen) :
    AperyAnalyticDisk where
  toAperyRegularDisk := d
  analytic := h

@[simp] lemma ofHasFPowerSeriesOnBall_toAperyRegularDisk
    (d : AperyRegularDisk) (p : FormalMultilinearSeries ℝ ℝ ℝ)
    (hp : HasFPowerSeriesOnBall d.F p d.center (ENNReal.ofReal d.radius)) :
    (ofHasFPowerSeriesOnBall d p hp).toAperyRegularDisk = d := rfl

@[simp] lemma ofAperyRegularDisk_toAperyRegularDisk
    (d : AperyRegularDisk) (h : AnalyticOnNhd ℝ d.F d.diskOpen) :
    (ofAperyRegularDisk d h).toAperyRegularDisk = d := rfl

/-- **Inhabitation from absolute summability.** The headline constructor
of this section: an `AperyRegularDisk` together with absolute summability
of `Σ |coeffs n| · r'^n` for every `r' ∈ [0, d.radius)` automatically
produces an `AperyAnalyticDisk`.

The radius hypothesis is exactly what one obtains from a Cauchy-Hadamard
or root-test bound on the coefficients. The constructor assembles a
`HasFPowerSeriesOnBall` witness with formal series
`FormalMultilinearSeries.ofScalars ℝ d.coeffs` at `d.center` of radius
`ENNReal.ofReal d.radius`, then dispatches to
`ofHasFPowerSeriesOnBall`. The three fields are discharged via:

* `r_le` ← `AperyRegularDisk.le_radius_ofScalars`
* `r_pos` ← `ENNReal.ofReal_pos.mpr d.radius_pos`
* `hasSum` ← `AperyRegularDisk.hasSum_ofScalars` -/
noncomputable def ofSummable
    (d : AperyRegularDisk)
    (hSum : ∀ r' : ℝ≥0, (r' : ℝ) < d.radius →
      Summable (fun n : ℕ => |d.coeffs n| * (r' : ℝ) ^ n)) :
    AperyAnalyticDisk :=
  ofHasFPowerSeriesOnBall d (FormalMultilinearSeries.ofScalars ℝ d.coeffs)
    { r_le := d.le_radius_ofScalars hSum
      r_pos := ENNReal.ofReal_pos.mpr d.radius_pos
      hasSum := fun hy => d.hasSum_ofScalars hy }

@[simp] lemma ofSummable_toAperyRegularDisk
    (d : AperyRegularDisk)
    (hSum : ∀ r' : ℝ≥0, (r' : ℝ) < d.radius →
      Summable (fun n : ℕ => |d.coeffs n| * (r' : ℝ) ^ n)) :
    (ofSummable d hSum).toAperyRegularDisk = d := rfl

/-- **Compatibility lifted from the underlying geometric disks.** Two
analytic disks are compatible iff their underlying geometric disks
are compatible (i.e., their `F` values agree on the overlap of the
open domains). -/
def Compatible (d₁ d₂ : AperyAnalyticDisk) : Prop :=
  AperyRegularDisk.Compatible d₁.toAperyRegularDisk d₂.toAperyRegularDisk

@[refl] lemma Compatible.refl (d : AperyAnalyticDisk) : Compatible d d :=
  AperyRegularDisk.Compatible.refl _

@[symm] lemma Compatible.symm {d₁ d₂ : AperyAnalyticDisk} (h : Compatible d₁ d₂) :
    Compatible d₂ d₁ :=
  AperyRegularDisk.Compatible.symm h

lemma Compatible.F_eq {d₁ d₂ : AperyAnalyticDisk} (h : Compatible d₁ d₂)
    {z : ℝ} (hz₁ : z ∈ d₁.toAperyRegularDisk.diskOpen)
    (hz₂ : z ∈ d₂.toAperyRegularDisk.diskOpen) :
    d₁.F z = d₂.F z :=
  AperyRegularDisk.Compatible.F_eq h hz₁ hz₂

open Classical in
/-- **Glued function on union.** Combine two compatible analytic disks
into a single function on the union of their open domains. Inside
`d₁.diskOpen` it equals `d₁.F`; otherwise it equals `d₂.F`. The
compatibility hypothesis ensures the choice is consistent on the
overlap. -/
noncomputable def Compatible.glue {d₁ d₂ : AperyAnalyticDisk}
    (_h : Compatible d₁ d₂) : ℝ → ℝ := fun z =>
  if z ∈ d₁.toAperyRegularDisk.diskOpen then d₁.F z else d₂.F z

lemma Compatible.glue_eq_F₁ {d₁ d₂ : AperyAnalyticDisk}
    (h : Compatible d₁ d₂) {z : ℝ}
    (hz : z ∈ d₁.toAperyRegularDisk.diskOpen) : h.glue z = d₁.F z := by
  unfold Compatible.glue
  rw [if_pos hz]

lemma Compatible.glue_eq_F₂ {d₁ d₂ : AperyAnalyticDisk}
    (h : Compatible d₁ d₂) {z : ℝ}
    (hz : z ∈ d₂.toAperyRegularDisk.diskOpen) : h.glue z = d₂.F z := by
  unfold Compatible.glue
  by_cases hz₁ : z ∈ d₁.toAperyRegularDisk.diskOpen
  · rw [if_pos hz₁]; exact h.F_eq hz₁ hz
  · rw [if_neg hz₁]

/-- **Identity Theorem for analytic disks.** If two analytic disks have
a preconnected overlap and their `F` values coincide eventually at
*some* point of the overlap, then they are compatible — agree on the
entire overlap. This wraps Mathlib's
`AnalyticOnNhd.eqOn_of_preconnected_of_eventuallyEq`. -/
lemma Compatible.of_eventuallyEq_of_preconnected_overlap
    {d₁ d₂ : AperyAnalyticDisk}
    (hpre : IsPreconnected
      (d₁.toAperyRegularDisk.diskOpen ∩ d₂.toAperyRegularDisk.diskOpen))
    {z₀ : ℝ}
    (hz₀ : z₀ ∈ d₁.toAperyRegularDisk.diskOpen ∩ d₂.toAperyRegularDisk.diskOpen)
    (hev : d₁.F =ᶠ[nhds z₀] d₂.F) :
    Compatible d₁ d₂ := by
  intro z hz₁ hz₂
  set S := d₁.toAperyRegularDisk.diskOpen ∩ d₂.toAperyRegularDisk.diskOpen with hS
  have h₁ : AnalyticOnNhd ℝ d₁.F S :=
    d₁.analytic.mono Set.inter_subset_left
  have h₂ : AnalyticOnNhd ℝ d₂.F S :=
    d₂.analytic.mono Set.inter_subset_right
  have heq : Set.EqOn d₁.F d₂.F S :=
    h₁.eqOn_of_preconnected_of_eventuallyEq h₂ hpre hz₀ hev
  exact heq ⟨hz₁, hz₂⟩

/-- **Transitivity of compatibility through a middle disk.** Given
`d₁ ~ d ~ d₂` (both pairwise compatible), a triple-overlap point
`z₀ ∈ d₁ ∩ d ∩ d₂`, and a preconnected `d₁ ∩ d₂`, conclude
`d₁ ~ d₂` on the *entire* overlap — not just at `z₀`.

The pointwise transitivity at `z₀` follows from `F_eq_trans`. To
extend it across the full overlap we need the Identity Theorem:
`d₁.F` and `d₂.F` agree on the open triple intersection (a
neighborhood of `z₀`), giving germ-equality at `z₀`, which then
propagates by `Compatible.of_eventuallyEq_of_preconnected_overlap`. -/
lemma Compatible.trans_of_preconnected {d₁ d d₂ : AperyAnalyticDisk}
    (h₁ : Compatible d₁ d) (h₂ : Compatible d d₂)
    (hpre : IsPreconnected
      (d₁.toAperyRegularDisk.diskOpen ∩ d₂.toAperyRegularDisk.diskOpen))
    {z₀ : ℝ}
    (hz₁ : z₀ ∈ d₁.toAperyRegularDisk.diskOpen)
    (hzm : z₀ ∈ d.toAperyRegularDisk.diskOpen)
    (hz₂ : z₀ ∈ d₂.toAperyRegularDisk.diskOpen) :
    Compatible d₁ d₂ := by
  apply Compatible.of_eventuallyEq_of_preconnected_overlap hpre ⟨hz₁, hz₂⟩
  have hopen :
      IsOpen (d₁.toAperyRegularDisk.diskOpen ∩
              d.toAperyRegularDisk.diskOpen ∩
              d₂.toAperyRegularDisk.diskOpen) :=
    ((d₁.toAperyRegularDisk.diskOpen_isOpen.inter
        d.toAperyRegularDisk.diskOpen_isOpen).inter
      d₂.toAperyRegularDisk.diskOpen_isOpen)
  apply Filter.eventually_of_mem (hopen.mem_nhds ⟨⟨hz₁, hzm⟩, hz₂⟩)
  rintro z ⟨⟨hz1, hzm'⟩, hz2⟩
  exact (h₁.F_eq hz1 hzm').trans (h₂.F_eq hzm' hz2)

/-- **Chain transitivity at a common anchor point.** If a sequence of
analytic disks `ds 0, ds 1, …, ds n` is pairwise consecutively
compatible, every disk contains a single common point `z₀`, and each
overlap `(ds 0).diskOpen ∩ (ds k).diskOpen` is preconnected, then the
endpoints `ds 0` and `ds n` are themselves compatible.

The hypothesis is strong (one anchor inside every disk of the chain),
but matches the natural use case for forward analytic continuation:
fix a base point in the initial disk and require every extension to
keep containing it. The proof is induction on `n` using
`trans_of_preconnected` at each step. -/
lemma Compatible.chain_at_common_point
    (ds : ℕ → AperyAnalyticDisk) (n : ℕ)
    (hpairs : ∀ k, k < n → Compatible (ds k) (ds (k + 1)))
    (z₀ : ℝ)
    (hz_all : ∀ k, k ≤ n → z₀ ∈ (ds k).toAperyRegularDisk.diskOpen)
    (hpre : ∀ k, k ≤ n →
      IsPreconnected
        ((ds 0).toAperyRegularDisk.diskOpen ∩ (ds k).toAperyRegularDisk.diskOpen)) :
    Compatible (ds 0) (ds n) := by
  induction n with
  | zero => exact Compatible.refl _
  | succ n ih =>
    have hpairs' : ∀ k, k < n → Compatible (ds k) (ds (k + 1)) :=
      fun k hk => hpairs k (Nat.lt_succ_of_lt hk)
    have hz_all' : ∀ k, k ≤ n → z₀ ∈ (ds k).toAperyRegularDisk.diskOpen :=
      fun k hk => hz_all k (Nat.le_succ_of_le hk)
    have hpre' : ∀ k, k ≤ n →
        IsPreconnected
          ((ds 0).toAperyRegularDisk.diskOpen ∩ (ds k).toAperyRegularDisk.diskOpen) :=
      fun k hk => hpre k (Nat.le_succ_of_le hk)
    have h0n : Compatible (ds 0) (ds n) := ih hpairs' hz_all' hpre'
    have hnn1 : Compatible (ds n) (ds (n + 1)) := hpairs n (Nat.lt_succ_self n)
    exact Compatible.trans_of_preconnected h0n hnn1
      (hpre (n + 1) (Nat.le_refl _))
      (hz_all 0 (Nat.zero_le _))
      (hz_all n (Nat.le_succ n))
      (hz_all (n + 1) (Nat.le_refl _))

/-- **Chain transitivity with per-step anchors.** Weaker hypothesis
than `chain_at_common_point`: instead of a single anchor in every
disk, only require, for each `k < n`, a point `zs k` simultaneously
in `(ds 0) ∩ (ds k) ∩ (ds (k+1))`. The triple-overlap point is
allowed to vary as the chain advances.

Each induction step uses `zs n` as the anchor for
`trans_of_preconnected`; the IH only consumes the per-step anchors
for `k < n`. -/
lemma Compatible.chain_with_pointwise_anchor
    (ds : ℕ → AperyAnalyticDisk) (n : ℕ)
    (hpairs : ∀ k, k < n → Compatible (ds k) (ds (k + 1)))
    (zs : ℕ → ℝ)
    (hz0 : ∀ k, k < n → zs k ∈ (ds 0).toAperyRegularDisk.diskOpen)
    (hzk : ∀ k, k < n → zs k ∈ (ds k).toAperyRegularDisk.diskOpen)
    (hzk1 : ∀ k, k < n → zs k ∈ (ds (k + 1)).toAperyRegularDisk.diskOpen)
    (hpre : ∀ k, k ≤ n →
      IsPreconnected
        ((ds 0).toAperyRegularDisk.diskOpen ∩ (ds k).toAperyRegularDisk.diskOpen)) :
    Compatible (ds 0) (ds n) := by
  induction n with
  | zero => exact Compatible.refl _
  | succ n ih =>
    have hpairs' : ∀ k, k < n → Compatible (ds k) (ds (k + 1)) :=
      fun k hk => hpairs k (Nat.lt_succ_of_lt hk)
    have hz0'   : ∀ k, k < n → zs k ∈ (ds 0).toAperyRegularDisk.diskOpen :=
      fun k hk => hz0 k (Nat.lt_succ_of_lt hk)
    have hzk'   : ∀ k, k < n → zs k ∈ (ds k).toAperyRegularDisk.diskOpen :=
      fun k hk => hzk k (Nat.lt_succ_of_lt hk)
    have hzk1'  : ∀ k, k < n → zs k ∈ (ds (k + 1)).toAperyRegularDisk.diskOpen :=
      fun k hk => hzk1 k (Nat.lt_succ_of_lt hk)
    have hpre'  : ∀ k, k ≤ n →
        IsPreconnected
          ((ds 0).toAperyRegularDisk.diskOpen ∩ (ds k).toAperyRegularDisk.diskOpen) :=
      fun k hk => hpre k (Nat.le_succ_of_le hk)
    have h0n  : Compatible (ds 0) (ds n) :=
      ih hpairs' hz0' hzk' hzk1' hpre'
    have hnn1 : Compatible (ds n) (ds (n + 1)) := hpairs n (Nat.lt_succ_self n)
    exact Compatible.trans_of_preconnected h0n hnn1
      (hpre (n + 1) (Nat.le_refl _))
      (hz0  n (Nat.lt_succ_self n))
      (hzk  n (Nat.lt_succ_self n))
      (hzk1 n (Nat.lt_succ_self n))

/-- **Chain transitivity, hypothesis-light variant.** Same as
`chain_with_pointwise_anchor` but the per-step `IsPreconnected`
hypothesis is dropped: in ℝ each open disk is convex, so any pairwise
overlap is automatically preconnected (`diskOpen_inter_isPreconnected`).
The user only needs to supply pairwise compatibility and the
sliding-anchor sequence. -/
lemma Compatible.chain_with_pointwise_anchor'
    (ds : ℕ → AperyAnalyticDisk) (n : ℕ)
    (hpairs : ∀ k, k < n → Compatible (ds k) (ds (k + 1)))
    (zs : ℕ → ℝ)
    (hz0 : ∀ k, k < n → zs k ∈ (ds 0).toAperyRegularDisk.diskOpen)
    (hzk : ∀ k, k < n → zs k ∈ (ds k).toAperyRegularDisk.diskOpen)
    (hzk1 : ∀ k, k < n → zs k ∈ (ds (k + 1)).toAperyRegularDisk.diskOpen) :
    Compatible (ds 0) (ds n) :=
  Compatible.chain_with_pointwise_anchor ds n hpairs zs hz0 hzk hzk1
    (fun _ _ => AperyRegularDisk.diskOpen_inter_isPreconnected _ _)

/-- **Common-anchor chain, hypothesis-light variant.** Drops the
preconnectedness side-condition of `chain_at_common_point`: pairwise
overlaps in ℝ are automatically preconnected. -/
lemma Compatible.chain_at_common_point'
    (ds : ℕ → AperyAnalyticDisk) (n : ℕ)
    (hpairs : ∀ k, k < n → Compatible (ds k) (ds (k + 1)))
    (z₀ : ℝ)
    (hz_all : ∀ k, k ≤ n → z₀ ∈ (ds k).toAperyRegularDisk.diskOpen) :
    Compatible (ds 0) (ds n) :=
  Compatible.chain_at_common_point ds n hpairs z₀ hz_all
    (fun _ _ => AperyRegularDisk.diskOpen_inter_isPreconnected _ _)

/-- **The glued function is analytic on the union of the two disks.**
At every point `z` of `d₁.diskOpen ∪ d₂.diskOpen`, the glue agrees
with whichever underlying `F` covers `z`, so it inherits analyticity
from `d₁.analytic` or `d₂.analytic`. This converts the abstract
piecewise glue into a genuine analytic continuation across the union. -/
lemma Compatible.glue_analyticOnNhd {d₁ d₂ : AperyAnalyticDisk}
    (h : Compatible d₁ d₂) :
    AnalyticOnNhd ℝ h.glue
      (d₁.toAperyRegularDisk.diskOpen ∪ d₂.toAperyRegularDisk.diskOpen) := by
  rintro z (hz₁ | hz₂)
  · have h1 : AnalyticAt ℝ d₁.F z := d₁.analytic z hz₁
    have hev : d₁.F =ᶠ[nhds z] h.glue := by
      apply Filter.eventually_of_mem
        ((d₁.toAperyRegularDisk.diskOpen_isOpen).mem_nhds hz₁)
      intro w hw
      exact (h.glue_eq_F₁ hw).symm
    exact h1.congr hev
  · have h2 : AnalyticAt ℝ d₂.F z := d₂.analytic z hz₂
    have hev : d₂.F =ᶠ[nhds z] h.glue := by
      apply Filter.eventually_of_mem
        ((d₂.toAperyRegularDisk.diskOpen_isOpen).mem_nhds hz₂)
      intro w hw
      exact (h.glue_eq_F₂ hw).symm
    exact h2.congr hev

/-- **Chain analytic extension on the union.** Given any function `G`
that agrees with each disk's `F` on its piece, `G` is analytic on the
entire chained union `⋃ k ≤ n, (ds k).diskOpen`. The hypothesis is
purely local: pairwise compatibility is what makes such a `G` exist
(via `Compatible.glue` iterated), but proving analyticity only needs
the per-piece agreement. -/
lemma analyticOnNhd_chain_union
    (ds : ℕ → AperyAnalyticDisk) (n : ℕ)
    (G : ℝ → ℝ)
    (hG : ∀ k, k ≤ n → ∀ z ∈ (ds k).toAperyRegularDisk.diskOpen,
      G z = (ds k).F z) :
    AnalyticOnNhd ℝ G
      (⋃ k ∈ Finset.range (n + 1), (ds k).toAperyRegularDisk.diskOpen) := by
  intro z hz
  rcases Set.mem_iUnion₂.mp hz with ⟨k, hkn, hzk⟩
  have hk : k ≤ n := Nat.lt_succ_iff.mp (Finset.mem_range.mp hkn)
  have hev : (ds k).F =ᶠ[nhds z] G := by
    apply Filter.eventually_of_mem
      ((ds k).toAperyRegularDisk.diskOpen_isOpen.mem_nhds hzk)
    intro w hw
    exact (hG k hk w hw).symm
  exact ((ds k).analytic z hzk).congr hev

end AperyAnalyticDisk

/-! ### Analytic disk at a regular point

The combined object: a Frobenius disk whose center is a regular point
of the conifold ODE (so the local expansion is an ordinary power series)
and whose `F` is real-analytic on the open disk (so the Identity Theorem
applies for chaining). This is the natural target object for the gap-B
forward-continuation pipeline: every disk in the chain is anchored at a
regular point of `(0, 1/64) ∪ …` and is analytic (so values transfer
through overlap by the Identity Theorem). -/

structure AperyAnalyticDiskAt extends AperyAnalyticDisk where
  /-- The center is a regular point of the conifold ODE. -/
  regular : AperyConifoldRegularPoint toAperyRegularDisk.center

namespace AperyAnalyticDiskAt

/-- **Project to the regular-center geometric disk.** -/
@[simp] def toAperyRegularDiskAt (d : AperyAnalyticDiskAt) :
    AperyRegularDiskAt where
  toAperyRegularDisk := d.toAperyRegularDisk
  regular := d.regular

/-- **Inhabitation from absolute summability at a regular center.**
Combines `AperyAnalyticDisk.ofSummable` with the regularity hypothesis
on the center. -/
noncomputable def ofSummable
    (d : AperyRegularDiskAt)
    (hSum : ∀ r' : ℝ≥0, (r' : ℝ) < d.toAperyRegularDisk.radius →
      Summable (fun n : ℕ => |d.toAperyRegularDisk.coeffs n| * (r' : ℝ) ^ n)) :
    AperyAnalyticDiskAt where
  toAperyAnalyticDisk := AperyAnalyticDisk.ofSummable d.toAperyRegularDisk hSum
  regular := d.regular

@[simp] lemma ofSummable_toAperyRegularDisk
    (d : AperyRegularDiskAt)
    (hSum : ∀ r' : ℝ≥0, (r' : ℝ) < d.toAperyRegularDisk.radius →
      Summable (fun n : ℕ => |d.toAperyRegularDisk.coeffs n| * (r' : ℝ) ^ n)) :
    (ofSummable d hSum).toAperyRegularDisk = d.toAperyRegularDisk := rfl

@[simp] lemma ofSummable_regular
    (d : AperyRegularDiskAt)
    (hSum : ∀ r' : ℝ≥0, (r' : ℝ) < d.toAperyRegularDisk.radius →
      Summable (fun n : ℕ => |d.toAperyRegularDisk.coeffs n| * (r' : ℝ) ^ n)) :
    (ofSummable d hSum).regular = d.regular := rfl

/-! #### Compatibility transfer with the underlying `At`-chain machinery -/

/-- **Compatibility lifted from the underlying regular-at disks.** Two
analytic-at disks are compatible iff their projections to
`AperyRegularDiskAt` are compatible. -/
def Compatible (d₁ d₂ : AperyAnalyticDiskAt) : Prop :=
  AperyRegularDiskAt.Compatible d₁.toAperyRegularDiskAt d₂.toAperyRegularDiskAt

@[refl] lemma Compatible.refl (d : AperyAnalyticDiskAt) : Compatible d d :=
  AperyRegularDiskAt.Compatible.refl _

@[symm] lemma Compatible.symm {d₁ d₂ : AperyAnalyticDiskAt} (h : Compatible d₁ d₂) :
    Compatible d₂ d₁ :=
  AperyRegularDiskAt.Compatible.symm h

lemma Compatible.F_eq {d₁ d₂ : AperyAnalyticDiskAt} (h : Compatible d₁ d₂)
    {z : ℝ} (hz₁ : z ∈ d₁.toAperyRegularDisk.diskOpen)
    (hz₂ : z ∈ d₂.toAperyRegularDisk.diskOpen) :
    d₁.F z = d₂.F z :=
  AperyRegularDiskAt.Compatible.F_eq h hz₁ hz₂

/-- **Compatibility upgrade:** the `AperyAnalyticDisk`-level compat between
underlying analytic disks is the same predicate as `AperyAnalyticDiskAt`-level
compat (both reduce to geometric `AperyRegularDisk.Compatible`). -/
lemma Compatible_iff_analytic {d₁ d₂ : AperyAnalyticDiskAt} :
    Compatible d₁ d₂ ↔
      AperyAnalyticDisk.Compatible d₁.toAperyAnalyticDisk d₂.toAperyAnalyticDisk :=
  Iff.rfl

/-- **Chain F-equality through a common point** (analytic-at version).
Drops to `AperyRegularDiskAt.Compatible.F_eq_chain` on the projected
chain. -/
lemma Compatible.F_eq_chain (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    (hcomp : ∀ i, i < n → Compatible (ds i) (ds (i + 1)))
    {z : ℝ} (hz : ∀ i, i ≤ n → z ∈ (ds i).toAperyRegularDisk.diskOpen) :
    (ds 0).F z = (ds n).F z :=
  AperyRegularDiskAt.Compatible.F_eq_chain
    (fun i => (ds i).toAperyRegularDiskAt) n hcomp hz

/-! #### Two-piece glue at the analytic-at layer -/

/-- **Glued function** between two compatible analytic-at disks. Reuses
the underlying `AperyAnalyticDisk.Compatible.glue`. -/
noncomputable def Compatible.glue {d₁ d₂ : AperyAnalyticDiskAt}
    (h : Compatible d₁ d₂) : ℝ → ℝ :=
  AperyAnalyticDisk.Compatible.glue (d₁ := d₁.toAperyAnalyticDisk)
    (d₂ := d₂.toAperyAnalyticDisk) h

lemma Compatible.glue_eq_F₁ {d₁ d₂ : AperyAnalyticDiskAt}
    (h : Compatible d₁ d₂) {z : ℝ}
    (hz : z ∈ d₁.toAperyRegularDisk.diskOpen) : h.glue z = d₁.F z :=
  AperyAnalyticDisk.Compatible.glue_eq_F₁ h hz

lemma Compatible.glue_eq_F₂ {d₁ d₂ : AperyAnalyticDiskAt}
    (h : Compatible d₁ d₂) {z : ℝ}
    (hz : z ∈ d₂.toAperyRegularDisk.diskOpen) : h.glue z = d₂.F z :=
  AperyAnalyticDisk.Compatible.glue_eq_F₂ h hz

lemma Compatible.glue_analyticOnNhd {d₁ d₂ : AperyAnalyticDiskAt}
    (h : Compatible d₁ d₂) :
    AnalyticOnNhd ℝ h.glue
      (d₁.toAperyRegularDisk.diskOpen ∪ d₂.toAperyRegularDisk.diskOpen) :=
  AperyAnalyticDisk.Compatible.glue_analyticOnNhd h

/-- **Chain analytic extension on the union (analytic-at version).** Mirrors
`AperyAnalyticDisk.analyticOnNhd_chain_union`: any function `G` agreeing
piecewise with each chained analytic-at disk's `F` is analytic on the
union of their open disks. The regular-center hypothesis on each disk is
not used here — analyticity is already carried by the underlying
`AperyAnalyticDisk` layer. -/
lemma analyticOnNhd_chain_union
    (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    (G : ℝ → ℝ)
    (hG : ∀ k, k ≤ n → ∀ z ∈ (ds k).toAperyRegularDisk.diskOpen,
      G z = (ds k).F z) :
    AnalyticOnNhd ℝ G
      (⋃ k ∈ Finset.range (n + 1), (ds k).toAperyRegularDisk.diskOpen) :=
  AperyAnalyticDisk.analyticOnNhd_chain_union
    (fun i => (ds i).toAperyAnalyticDisk) n G hG

/-! #### N-piece chain glue construction -/

open Classical in
/-- **N-piece chain glue.** Given a sequence of analytic-at disks, defines a
single function on `ℝ` that on each disk's interior equals the disk's `F`,
provided the per-point values are consistent across all containing disks.
Picks the value from the lowest-indexed containing disk; returns `0`
where no disk contains `z`. -/
noncomputable def chainGlue (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ) : ℝ → ℝ :=
  fun z =>
    if h : ∃ k, k ≤ n ∧ z ∈ (ds k).toAperyRegularDisk.diskOpen then
      (ds (Nat.find h)).F z
    else 0

/-- **Per-piece value of chain glue.** Under transitive value-consistency
across containing disks, `chainGlue` equals each piece's `F` on that
piece's open disk. -/
lemma chainGlue_eq (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    (hCons : ∀ j k z, j ≤ n → k ≤ n →
      z ∈ (ds j).toAperyRegularDisk.diskOpen →
      z ∈ (ds k).toAperyRegularDisk.diskOpen →
      (ds j).F z = (ds k).F z)
    {k : ℕ} (hk : k ≤ n) {z : ℝ}
    (hz : z ∈ (ds k).toAperyRegularDisk.diskOpen) :
    chainGlue ds n z = (ds k).F z := by
  classical
  unfold chainGlue
  have hex : ∃ k', k' ≤ n ∧ z ∈ (ds k').toAperyRegularDisk.diskOpen := ⟨k, hk, hz⟩
  rw [dif_pos hex]
  have hj := Nat.find_spec hex
  exact hCons (Nat.find hex) k z hj.1 hk hj.2 hz

/-- **Analyticity of the chain glue** on the union. Combines `chainGlue_eq`
with `analyticOnNhd_chain_union`. -/
lemma chainGlue_analyticOnNhd (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    (hCons : ∀ j k z, j ≤ n → k ≤ n →
      z ∈ (ds j).toAperyRegularDisk.diskOpen →
      z ∈ (ds k).toAperyRegularDisk.diskOpen →
      (ds j).F z = (ds k).F z) :
    AnalyticOnNhd ℝ (chainGlue ds n)
      (⋃ k ∈ Finset.range (n + 1), (ds k).toAperyRegularDisk.diskOpen) :=
  analyticOnNhd_chain_union ds n (chainGlue ds n)
    (fun _ hk _ hz => chainGlue_eq ds n hCons hk hz)

/-! #### Caller-friendly variants from all-pairs `Compatible` -/

/-- **Transitive value-consistency from all-pairs Compatible.** If every
pair of disks in the chain is `Compatible` (vacuously so on empty overlap;
nontrivially so on actual overlaps), then values agree on every shared
point. Direct corollary of `Compatible.F_eq`. -/
lemma cons_of_pairwise_compatible (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    (hcompat : ∀ j k, j ≤ n → k ≤ n → Compatible (ds j) (ds k)) :
    ∀ j k z, j ≤ n → k ≤ n →
      z ∈ (ds j).toAperyRegularDisk.diskOpen →
      z ∈ (ds k).toAperyRegularDisk.diskOpen →
      (ds j).F z = (ds k).F z :=
  fun j k _ hj hk hzj hzk =>
    Compatible.F_eq (hcompat j k hj hk) hzj hzk

/-- **Per-piece value of chain glue under all-pairs Compatible.** -/
lemma chainGlue_eq_of_pairwise_compatible
    (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    (hcompat : ∀ j k, j ≤ n → k ≤ n → Compatible (ds j) (ds k))
    {k : ℕ} (hk : k ≤ n) {z : ℝ}
    (hz : z ∈ (ds k).toAperyRegularDisk.diskOpen) :
    chainGlue ds n z = (ds k).F z :=
  chainGlue_eq ds n (cons_of_pairwise_compatible ds n hcompat) hk hz

/-- **Analyticity of chain glue under all-pairs Compatible.** -/
lemma chainGlue_analyticOnNhd_of_pairwise_compatible
    (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    (hcompat : ∀ j k, j ≤ n → k ≤ n → Compatible (ds j) (ds k)) :
    AnalyticOnNhd ℝ (chainGlue ds n)
      (⋃ k ∈ Finset.range (n + 1), (ds k).toAperyRegularDisk.diskOpen) :=
  chainGlue_analyticOnNhd ds n (cons_of_pairwise_compatible ds n hcompat)

/-! #### Monotonicity in chain length -/

/-- **Chain glue is monotone in length.** Extending a compatible chain
beyond `m` to `n ≥ m` does not change the chain-glue value at any point
already covered by some disk up to index `m`. The hypothesis is supplied
at the larger index `n`; the smaller-index consistency is a restriction. -/
lemma chainGlue_eq_of_le {m n : ℕ} (hmn : m ≤ n)
    (ds : ℕ → AperyAnalyticDiskAt)
    (hCons_n : ∀ j k z, j ≤ n → k ≤ n →
      z ∈ (ds j).toAperyRegularDisk.diskOpen →
      z ∈ (ds k).toAperyRegularDisk.diskOpen →
      (ds j).F z = (ds k).F z)
    {z : ℝ} {k : ℕ} (hk : k ≤ m)
    (hz : z ∈ (ds k).toAperyRegularDisk.diskOpen) :
    chainGlue ds m z = chainGlue ds n z := by
  have hCons_m : ∀ j k z, j ≤ m → k ≤ m →
      z ∈ (ds j).toAperyRegularDisk.diskOpen →
      z ∈ (ds k).toAperyRegularDisk.diskOpen →
      (ds j).F z = (ds k).F z :=
    fun j k z hj hk' => hCons_n j k z (hj.trans hmn) (hk'.trans hmn)
  rw [chainGlue_eq ds m hCons_m hk hz,
      chainGlue_eq ds n hCons_n (hk.trans hmn) hz]

/-- **Chain glue monotonicity under all-pairs Compatible.** -/
lemma chainGlue_eq_of_le_of_pairwise_compatible {m n : ℕ} (hmn : m ≤ n)
    (ds : ℕ → AperyAnalyticDiskAt)
    (hcompat : ∀ j k, j ≤ n → k ≤ n → Compatible (ds j) (ds k))
    {z : ℝ} {k : ℕ} (hk : k ≤ m)
    (hz : z ∈ (ds k).toAperyRegularDisk.diskOpen) :
    chainGlue ds m z = chainGlue ds n z :=
  chainGlue_eq_of_le hmn ds (cons_of_pairwise_compatible ds n hcompat) hk hz

/-! #### Off-chain default behaviour -/

/-- **Chain glue is `0` outside the chain union.** When `z` is not
contained in any of `(ds 0).diskOpen, …, (ds n).diskOpen`, the
`chainGlue` definition falls through to its default value `0`. -/
lemma chainGlue_eq_zero_of_notMem (ds : ℕ → AperyAnalyticDiskAt) (n : ℕ)
    {z : ℝ}
    (hz : ∀ k, k ≤ n → z ∉ (ds k).toAperyRegularDisk.diskOpen) :
    chainGlue ds n z = 0 := by
  classical
  unfold chainGlue
  have hex : ¬ ∃ k, k ≤ n ∧ z ∈ (ds k).toAperyRegularDisk.diskOpen := by
    rintro ⟨k, hk, hzk⟩
    exact hz k hk hzk
  rw [dif_neg hex]

/-- **New-point coverage: smaller-chain default vs larger-chain value.**
If `z` lies in no disk up to index `m` but does lie in some disk in the
range `[m+1, n]`, then `chainGlue ds m z = 0` while
`chainGlue ds n z = (ds k).F z` for the witnessing `k`. The two values
need not coincide, exhibiting the non-monotonicity of chain glue at
boundary points (extension genuinely brings in new analytic data). -/
lemma chainGlue_smaller_zero_larger_F
    (ds : ℕ → AperyAnalyticDiskAt) (m n : ℕ)
    (hCons_n : ∀ j k z, j ≤ n → k ≤ n →
      z ∈ (ds j).toAperyRegularDisk.diskOpen →
      z ∈ (ds k).toAperyRegularDisk.diskOpen →
      (ds j).F z = (ds k).F z)
    {z : ℝ}
    (hz_m : ∀ k, k ≤ m → z ∉ (ds k).toAperyRegularDisk.diskOpen)
    {k : ℕ} (hk : k ≤ n)
    (hzk : z ∈ (ds k).toAperyRegularDisk.diskOpen) :
    chainGlue ds m z = 0 ∧ chainGlue ds n z = (ds k).F z :=
  ⟨chainGlue_eq_zero_of_notMem ds m hz_m,
   chainGlue_eq ds n hCons_n hk hzk⟩

end AperyAnalyticDiskAt

end Frobenius
end Ripple
