import Ripple.PopulationProtocol.Majority.ExactMajority.Probability.StableBridges
open ExactMajority
#print axioms forall_output_A_of_wrongACount_zero
#print axioms forall_output_T_of_wrongTCount_zero
#print axioms phase10Majority_drained_mem_stableDone
#print axioms phase10Tie_drained_mem_stableDone
#print axioms phase10Majority_bridge_expectedHitting
#print axioms phase10Tie_bridge_expectedHitting
#print axioms phase10Majority_link_intersected
#print axioms phase10Tie_link_intersected
#print axioms ladderData_of_phase10Majority_bridged
#print axioms ladderData_of_phase10Tie_bridged
#print axioms timed_phase_chain_target
#print axioms timed_chain_target_is_next_phase
