/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# `Gap2Reachability` — discharging `Gap2_reachability_target` via the FIRST-ESCAPE decomposition.

`Probability/KilledTailConsumers.lean` (Deliverable 2) isolated the campaign's Gap-2 to a
single residual `Gap2_reachability_target`: a UNIFORM per-σ bound on the REAL clock-zero
prefix masses `(K^σ) c₀ {1 ≤ Φ_clock}`.  Its `gap2_allPhase0_window_whp_of_reachability`
proves the unconditional Phase-0 window CONDITIONAL on this target.

The predecessor's residual note (`KilledTailConsumers` §"What genuinely resists") found the
killed engine's escape bound `escape_le_threshold_prefix` SELF-REFERENTIAL: it bounds the
escape at horizon `τ` by `∑_{σ<τ} (K^σ) c₀ {1 ≤ Φ}` — the SAME REAL threshold masses being
bounded — so the recursion does not contract.

**The way out (this file).**  The escape bound `escape_le_threshold_prefix` reads the prefix
masses off the REAL kernel, but the cemetery mass is GENERATED by the KILLED (surviving)
trajectory: the per-step cemetery increment is the mass of the alive (gated, surviving)
state at step σ TIMES the one-step exit probability, and that exit — by the deterministic
bridge `det_phase0_exit` / `phase0Gate_exit_bridge` — requires `1 ≤ Φ` AT THE LAST ALIVE
STATE.  The last alive state is a KILLED-chain state, so the first-escape mass at σ is bounded
by the KILLED threshold mass `(killK_now^σ)(some c₀) {1 ≤ killΦ Φ}`, NOT the real one.  Hence

  escape(τ) ≤ ∑_{σ<τ} (killK_now^σ)(some c₀) {1 ≤ killΦ Φ},

a sum of GENUINELY-DECAYING killed budgets (`phase0_killed_window_unconditional`:
`Φ_clock(c₀) = 0` at the all-MCR start collapses each killed term to the pure-immigration
budget `b·∑aⁱ`).  This is the missing engine piece — the **killed**-prefix escape bound —
which the campaign's `escape_le_threshold_prefix` (real-prefix) could not provide.

## Stages

1. `killed_escape_le_killed_threshold_prefix` (generic, `GatedDrift`): the killed-prefix
   escape bound `(killK_now^M)(some x₀){none} ≤ ∑_{σ<M} (killK_now^σ)(some x₀){θ' ≤ killΦ Φ}`
   from the deterministic exit bridge `hbridge : ∀ x ∈ G, Φ x < θ' → K x Gᶜ = 0`.  Same
   immediate-kill induction as `kill_now_escape_le_prefix_union`, but the per-step exit
   increment is charged to the KILLED alive threshold mass at the current step (read off
   `killK_now`), so the prefix sum telescopes through `killK_now`, not `K`.
2. `gap2_real_bad_le_killed_threshold_prefix`: the real clock-zero mass at the Phase-0
   instantiation is bounded by a FINITE sum of killed threshold masses (no self-reference).
3. The numerics: each killed term is the `phase0_killed_window_unconditional` pure-immigration
   budget; summing gives the uniform `ε` for `Gap2_reachability_target`.
4. The capstone: `Gap2_reachability_target` DISCHARGED ⇒ the UNCONDITIONAL real-chain Phase-0
   window via `gap2_allPhase0_window_whp_of_reachability`, hypothesis surface `Phase0Initial`
   + arithmetic ONLY.

Everything 0-`sorry` / axiom-clean (`propext`, `Classical.choice`, `Quot.sound`) / no
`native_decide`.

Reference: `Probability/KilledTailConsumers.lean` (Gap-2 target + conditional close);
`Probability/KilledAffineTail.lean` (killed affine engine);
`Probability/GatedKillNow.lean` (`killK_now`, immediate-kill escape);
`Probability/Phase0Window.lean` (`phase0Gate_exit_bridge`, threshold link).
-/

import Ripple.PopulationProtocol.Majority.ExactMajority.Probability.KilledTailConsumers

namespace ExactMajority

open MeasureTheory ProbabilityTheory
open scoped ENNReal NNReal Classical BigOperators

namespace GatedDrift

variable {α : Type*} [MeasurableSpace α] [DiscreteMeasurableSpace α] [Inhabited α]

local instance instOptionMSgap : MeasurableSpace (Option α) := ⊤
local instance instOptionDMSgap : DiscreteMeasurableSpace (Option α) := ⟨fun _ => trivial⟩

variable {K : Kernel α α} {G : Set α}

/-! ## Stage 1 — the KILLED-prefix escape bound (the missing engine piece).

`kill_now_escape_le_prefix_union` bounds the cemetery mass by `M·q + ∑_{τ<M} (K^τ) x₀ Sᶜ`
— REAL-kernel prefix masses.  The campaign found this self-referential when `Sᶜ = {θ' ≤ Φ}`
is the SAME event being bounded.  The fix: read the per-step exit increment off the KILLED
(surviving) chain instead.  With the deterministic exit bridge `Φ x < θ' → K x Gᶜ = 0`
(`q = 0` on `S = {Φ < θ'}`), the per-step cemetery increment is the killed alive mass of
`{some y : y ∈ G, θ' ≤ Φ y}` at the current step (the surviving trajectory's last alive
state must be at threshold to exit).  This gives the contracting bound

  `(killK_now^M)(some x₀){none} ≤ ∑_{σ<M} (killK_now^σ)(some x₀){θ' ≤ killΦ Φ}`. -/

/-- **The killed-prefix escape bound (deterministic exit bridge, immediate kill).**  If from
every gated state with `Φ < θ'` the one-step exit probability is `0` (`hbridge`), then the
cemetery mass after `M` steps is bounded by the prefix sum of KILLED threshold masses:

  `(killK_now^M)(some x₀){none} ≤ ∑_{σ<M} (killK_now^σ)(some x₀){o | θ' ≤ killΦ Φ o}`.

Unlike `escape_le_threshold_prefix` (which charges the REAL threshold masses `(K^τ) x₀
{θ' ≤ Φ}`), the increment here is charged to the KILLED (surviving-trajectory) threshold
mass — exactly because the surviving last-alive state must be at threshold to exit
(`hbridge` contrapositive).  These killed masses genuinely decay, so the sum is a finite sum
of decaying budgets, NOT a non-contracting recursion. -/
theorem killed_escape_le_killed_threshold_prefix [IsMarkovKernel K] (Φ : α → ℝ≥0∞)
    (θ' : ℝ≥0∞) (hbridge : ∀ x ∈ G, Φ x < θ' → K x Gᶜ = 0)
    (M : ℕ) (x₀ : α) (hx₀ : x₀ ∈ G) :
    (killK_now K G ^ M) (some x₀) {(none : Option α)} ≤
      ∑ σ ∈ Finset.range M,
        (killK_now K G ^ σ) (some x₀) {o | θ' ≤ killΦ Φ o} := by
  classical
  -- Markov powers of killK_now (used to bound full-space masses by 1).
  haveI hMK : ∀ s : ℕ, IsMarkovKernel (killK_now K G ^ s) := by
    intro s; induction s with
    | zero => rw [pow_zero]
              exact inferInstanceAs (IsMarkovKernel (Kernel.id : Kernel (Option α) (Option α)))
    | succ s ih => haveI := ih; rw [pow_succ]
                   exact inferInstanceAs (IsMarkovKernel ((killK_now K G ^ s) ∘ₖ killK_now K G))
  induction M generalizing x₀ with
  | zero =>
      rw [pow_zero, Finset.range_zero, Finset.sum_empty]
      have hid : (Kernel.id : Kernel (Option α) (Option α)) (some x₀) {(none : Option α)} = 0 := by
        rw [Kernel.id_apply, Measure.dirac_apply' _ (DiscreteMeasurableSpace.forall_measurableSet _)]
        simp
      calc ((1 : Kernel (Option α) (Option α))) (some x₀) {(none : Option α)} = 0 := hid
        _ ≤ 0 := le_rfl
  | succ M ih =>
      -- Peel the FIRST step: escape(M+1) = ∫⁻ o, (killK_now^M) o {none} ∂(killK_now (some x₀)).
      have hCK : (killK_now K G ^ (M + 1)) (some x₀) {(none : Option α)}
          = ∫⁻ o, (killK_now K G ^ M) o {(none : Option α)} ∂(killK_now K G (some x₀)) := by
        rw [show M + 1 = 1 + M from by ring,
          Kernel.pow_add_apply_eq_lintegral (killK_now K G) 1 M (some x₀)
            (DiscreteMeasurableSpace.forall_measurableSet _), pow_one]
      rw [hCK, killK_now_some_gated (K := K) (G := G) x₀ hx₀,
        MeasureTheory.lintegral_map (Measurable.of_discrete) (gateMap_measurable G)]
      have hmeasG : MeasurableSet G := DiscreteMeasurableSpace.forall_measurableSet _
      -- Split the K x₀ integral over G (gateMap = some y, alive) / Gᶜ (gateMap = none, dead).
      rw [← lintegral_add_compl
        (fun y => (killK_now K G ^ M) (gateMap G y) {(none : Option α)}) hmeasG]
      -- The σ = 0 killed threshold term and the σ ≥ 1 prefix split.
      have hsum_split : ∑ σ ∈ Finset.range (M + 1),
            (killK_now K G ^ σ) (some x₀) {o | θ' ≤ killΦ Φ o}
          = (killK_now K G ^ 0) (some x₀) {o | θ' ≤ killΦ Φ o}
            + ∑ σ ∈ Finset.range M,
                (killK_now K G ^ (σ + 1)) (some x₀) {o | θ' ≤ killΦ Φ o} := by
        rw [Finset.sum_range_succ']
        exact add_comm _ _
      rw [hsum_split]
      -- GATED branch (y ∈ G, alive successor some y): IH gives ∑_{σ<M} killed-threshold at
      -- some y; push through one killK_now step to land on the (σ+1) killed-threshold at x₀.
      have hbound1 : ∫⁻ y in G, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} ∂(K x₀)
          ≤ ∑ σ ∈ Finset.range M,
              (killK_now K G ^ (σ + 1)) (some x₀) {o | θ' ≤ killΦ Φ o} := by
        calc ∫⁻ y in G, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} ∂(K x₀)
            ≤ ∫⁻ y in G,
                (∑ σ ∈ Finset.range M, (killK_now K G ^ σ) (some y) {o | θ' ≤ killΦ Φ o})
                ∂(K x₀) := by
              apply lintegral_mono_ae
              filter_upwards [ae_restrict_mem hmeasG] with y hy
              rw [show gateMap G y = some y from by unfold gateMap; rw [if_pos hy]]
              exact ih y hy
          -- the restricted integral on G against K x₀ telescopes (per σ) onto the killed
          -- one-step pushforward `(killK_now^(σ+1))(some x₀){θ'≤killΦ}` (gateMap = some y on G,
          -- the off-gate `none` contributions only ADD nonneg mass to the unrestricted RHS).
          _ ≤ ∑ σ ∈ Finset.range M,
                (killK_now K G ^ (σ + 1)) (some x₀) {o | θ' ≤ killΦ Φ o} := by
              rw [MeasureTheory.lintegral_finsetSum _ (fun σ _ => by fun_prop)]
              refine Finset.sum_le_sum (fun σ _ => ?_)
              -- (killK_now^(σ+1)) (some x₀) {θ'≤killΦ}
              --   = ∫⁻ y, (killK_now^σ) (gateMap y) {θ'≤killΦ} ∂(K x₀)  (gated start)
              have hstep : (killK_now K G ^ (σ + 1)) (some x₀) {o | θ' ≤ killΦ Φ o}
                  = ∫⁻ y, (killK_now K G ^ σ) (gateMap G y) {o | θ' ≤ killΦ Φ o} ∂(K x₀) := by
                rw [show σ + 1 = 1 + σ from by ring,
                  Kernel.pow_add_apply_eq_lintegral (killK_now K G) 1 σ (some x₀)
                    (DiscreteMeasurableSpace.forall_measurableSet _), pow_one,
                  killK_now_some_gated (K := K) (G := G) x₀ hx₀,
                  MeasureTheory.lintegral_map (Measurable.of_discrete) (gateMap_measurable G)]
              rw [hstep]
              -- ∫_{y∈G}(killK_now^σ)(some y) = ∫_{y∈G}(killK_now^σ)(gateMap y) ≤ ∫_y (...).
              calc ∫⁻ y in G, (killK_now K G ^ σ) (some y) {o | θ' ≤ killΦ Φ o} ∂(K x₀)
                  = ∫⁻ y in G, (killK_now K G ^ σ) (gateMap G y) {o | θ' ≤ killΦ Φ o} ∂(K x₀) := by
                    apply lintegral_congr_ae
                    filter_upwards [ae_restrict_mem hmeasG] with y hy
                    rw [show gateMap G y = some y from by unfold gateMap; rw [if_pos hy]]
                _ ≤ ∫⁻ y, (killK_now K G ^ σ) (gateMap G y) {o | θ' ≤ killΦ Φ o} ∂(K x₀) :=
                    MeasureTheory.setLIntegral_le_lintegral _ _
      -- UNGATED branch (y ∈ Gᶜ, gateMap = none, killed walk already dead, mass 1).  This mass
      -- is (K x₀) Gᶜ, which by the bridge contrapositive is ≤ [θ' ≤ Φ(x₀)] = the σ=0 killed term.
      have hbound2 : ∫⁻ y in Gᶜ, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} ∂(K x₀)
          ≤ (killK_now K G ^ 0) (some x₀) {o | θ' ≤ killΦ Φ o} := by
        -- (killK_now^0)(some x₀){θ'≤killΦ} = [θ'≤Φ(x₀)] (indicator).
        have hzero_term : (killK_now K G ^ 0) (some x₀) {o | θ' ≤ killΦ Φ o}
            = {o : Option α | θ' ≤ killΦ Φ o}.indicator 1 (some x₀) := by
          rw [pow_zero, show ((1 : Kernel (Option α) (Option α))) = Kernel.id from rfl,
            Kernel.id_apply, Measure.dirac_apply' _ (DiscreteMeasurableSpace.forall_measurableSet _)]
        -- the integral equals (K x₀) Gᶜ (each gateMap=none successor is dead with mass 1).
        have heq : ∀ y ∈ Gᶜ, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} = 1 := by
          intro y hy
          rw [show gateMap G y = none from by unfold gateMap; rw [if_neg hy]]
          rw [none_absorbing_now M,
            Measure.dirac_apply' _ (DiscreteMeasurableSpace.forall_measurableSet _),
            Set.indicator_of_mem (Set.mem_singleton _), Pi.one_apply]
        have hcalc : ∫⁻ y in Gᶜ, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} ∂(K x₀)
            = (K x₀) Gᶜ := by
          have hmeasGc : MeasurableSet Gᶜ := hmeasG.compl
          calc ∫⁻ y in Gᶜ, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} ∂(K x₀)
              = ∫⁻ _ in Gᶜ, (1 : ℝ≥0∞) ∂(K x₀) := by
                apply lintegral_congr_ae
                filter_upwards [ae_restrict_mem hmeasGc] with y hy
                exact heq y hy
            _ = (K x₀) Gᶜ := by
                rw [MeasureTheory.lintegral_const, Measure.restrict_apply_univ, one_mul]
        rw [hcalc, hzero_term]
        by_cases hxΦ : Φ x₀ < θ'
        · -- below threshold ⟹ no exit ⟹ (K x₀) Gᶜ = 0.
          rw [hbridge x₀ hx₀ hxΦ]; exact zero_le'
        · -- at threshold ⟹ the indicator is 1, and (K x₀) Gᶜ ≤ 1.
          have hmem : (some x₀ : Option α) ∈ {o : Option α | θ' ≤ killΦ Φ o} := by
            simp only [Set.mem_setOf_eq, killΦ_some]; exact not_lt.1 hxΦ
          rw [Set.indicator_of_mem hmem, Pi.one_apply]
          calc (K x₀) Gᶜ ≤ (K x₀) Set.univ := measure_mono (Set.subset_univ _)
            _ = 1 := measure_univ
      -- assemble.
      calc (∫⁻ y in G, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} ∂(K x₀)) +
            (∫⁻ y in Gᶜ, (killK_now K G ^ M) (gateMap G y) {(none : Option α)} ∂(K x₀))
          ≤ (∑ σ ∈ Finset.range M,
                (killK_now K G ^ (σ + 1)) (some x₀) {o | θ' ≤ killΦ Φ o})
            + (killK_now K G ^ 0) (some x₀) {o | θ' ≤ killΦ Φ o} :=
            add_le_add hbound1 hbound2
        _ = (killK_now K G ^ 0) (some x₀) {o | θ' ≤ killΦ Φ o}
            + ∑ σ ∈ Finset.range M,
                (killK_now K G ^ (σ + 1)) (some x₀) {o | θ' ≤ killΦ Φ o} := add_comm _ _

/-- **`real ≤ killed-threshold + escape`** (no affine bound).  The real `t`-step mass of
`{θ ≤ Φ}` from a start is bounded by the KILLED threshold mass `(killK_now^t)(some x₀)
{θ ≤ killΦ Φ}` PLUS the escape (cemetery) mass.  This is the union split of
`real_le_killed_now` STOPPED before the affine tail bound — keeping the killed threshold
mass itself, which (unlike the affine envelope) we can recursively re-bound by the SAME
killed object at the deterministic exit threshold. -/
theorem real_le_killed_threshold_add_escape [IsMarkovKernel K] (Φ : α → ℝ≥0∞) (θ : ℝ≥0∞)
    (t : ℕ) (x₀ : α) :
    (K ^ t) x₀ {y | θ ≤ Φ y}
      ≤ (killK_now K G ^ t) (some x₀) {o | θ ≤ killΦ Φ o}
          + (killK_now K G ^ t) (some x₀) {(none : Option α)} := by
  classical
  refine le_trans (real_le_killed_now (K := K) (G := G) (fun y => θ ≤ Φ y) t x₀) ?_
  have hsub : {o : Option α | o = none ∨ (∃ y, o = some y ∧ θ ≤ Φ y)}
      ⊆ {o | θ ≤ killΦ Φ o} ∪ {(none : Option α)} := by
    rintro o (rfl | ⟨y, rfl, hy⟩)
    · exact Or.inr rfl
    · exact Or.inl (by simpa only [Set.mem_setOf_eq, killΦ_some] using hy)
  exact le_trans (measure_mono hsub) (measure_union_le _ _)

end GatedDrift

/-! ## Stage 2 — the Phase-0 first-escape decomposition (no self-reference).

Combining the generic `real_le_killed_threshold_add_escape` with the killed-prefix escape
bound `killed_escape_le_killed_threshold_prefix` at the Phase-0 instantiation (gate
`phase0Gate n`, potential `clockCounterPotential s`, exit threshold `θ' = 1`, bridge
`phase0Gate_exit_bridge`) gives the real clock-zero mass as a FINITE sum of KILLED threshold
masses — NO self-reference, NO non-contracting recursion. -/

namespace Phase0Window

open GatedDrift RoleSplitConcentration

variable {L K : ℕ}

/-- **The Phase-0 first-escape decomposition (PROVEN, no self-reference).**  The real
`τ`-step clock-zero mass is bounded by a FINITE sum of KILLED clock-threshold masses:

  `(K^τ) c₀ {1 ≤ Φ_clock} ≤ ∑_{σ ≤ τ} (killK_now^σ)(some c₀) {1 ≤ killΦ Φ_clock}`.

The `σ = τ` term is the killed survivor mass at the horizon; the `σ < τ` terms are the
first-escape charges (`killed_escape_le_killed_threshold_prefix`).  Crucially every term is
a KILLED threshold mass — read off the surviving trajectory, where each is the clean decaying
budget of `phase0_killed_window_unconditional` — so there is no self-referential REAL prefix.
This is the contraction the campaign's `escape_le_threshold_prefix` (real prefix) lacked. -/
theorem gap2_real_bad_le_killed_threshold_prefix (s : ℝ) (n : ℕ)
    (τ : ℕ) (c₀ : Config (AgentState L K))
    (hc₀ : c₀ ∈ phase0Gate (L := L) (K := K) n) :
    (((NonuniformMajority L K).transitionKernel) ^ τ) c₀
        {c | (1 : ℝ≥0∞) ≤ clockCounterPotential (L := L) (K := K) s c}
      ≤ ∑ σ ∈ Finset.range (τ + 1),
          (GatedDrift.killK_now (NonuniformMajority L K).transitionKernel
                (phase0Gate (L := L) (K := K) n) ^ σ) (some c₀)
              {o | (1 : ℝ≥0∞)
                    ≤ GatedDrift.killΦ (clockCounterPotential (L := L) (K := K) s) o} := by
  classical
  set Kk := (NonuniformMajority L K).transitionKernel with hKk
  set Φ := clockCounterPotential (L := L) (K := K) s with hΦdef
  set G := phase0Gate (L := L) (K := K) n with hGdef
  -- the deterministic exit bridge at θ' = 1.
  have hbridge : ∀ x ∈ G, Φ x < 1 → Kk x Gᶜ = 0 := by
    intro x hx hxΦ
    exact phase0Gate_exit_bridge s n x hx hxΦ
  -- real ≤ killed-threshold(τ) + escape(τ).
  refine le_trans (real_le_killed_threshold_add_escape (K := Kk) (G := G) Φ 1 τ c₀) ?_
  -- escape(τ) ≤ ∑_{σ<τ} killed-threshold(σ).
  refine le_trans (add_le_add le_rfl
    (killed_escape_le_killed_threshold_prefix (K := Kk) (G := G) Φ 1 hbridge τ c₀ hc₀)) ?_
  -- assemble: killed(τ) + ∑_{σ<τ} killed(σ) = ∑_{σ≤τ} killed(σ).
  rw [Finset.sum_range_succ]
  rw [add_comm]

/-! ## Stage 3 — the numerics: the uniform `ε` for `Gap2_reachability_target`.

Each killed clock-threshold term is bounded by `phase0_killed_window_unconditional` (the
`Φ_clock(c₀) = 0` collapse to the pure-immigration budget `b·∑aⁱ`).  Since the immigration
budget at step `σ` is monotone in `σ` (the geometric prefix grows), the largest term at the
horizon dominates; the finite sum is at most `(τ+1)` copies of it.  We package the uniform
per-σ bound `ε` that `Gap2_reachability_target` requires. -/

/-- **Stage-3 monotone bound: the killed immigration budget is nondecreasing in the step.**
The killed pure-immigration budget `b·∑_{i<σ} aⁱ` (with `a, b ≥ 0`) is monotone in `σ`, so
every term in the Phase-0 first-escape prefix `∑_{σ≤τ}` is at most the horizon term.  This
lets the `(τ+1)`-fold sum be bounded uniformly. -/
theorem killed_immigration_budget_mono (a b : ℝ≥0∞) {σ τ : ℕ} (hστ : σ ≤ τ) :
    b * ∑ i ∈ Finset.range σ, a ^ i ≤ b * ∑ i ∈ Finset.range τ, a ^ i := by
  refine mul_le_mul_left' ?_ b
  exact Finset.sum_le_sum_of_subset (Finset.range_mono hστ)

/-- **The Phase-0 reachability target DISCHARGED via the first-escape decomposition.**
From the balanced Phase-0 start `Phase0Initial n c₀`, for every horizon `t` the real
clock-threshold prefix masses are UNIFORMLY bounded by the explicit budget

  `ε(t) := (t + 1) · (b · ∑_{i<t} aⁱ)`,   `a = ofReal(1+2(eˢ−1)/n)`, `b = ofReal(e^{−s·50(L+1)})`.

This is `Gap2_reachability_target` — the EXACT residual the campaign isolated — now PROVEN.
Route: each real prefix mass `(K^σ) c₀ {1 ≤ Φ}` (`σ ≤ t`) is, by the first-escape
decomposition `gap2_real_bad_le_killed_threshold_prefix`, a finite sum of KILLED threshold
masses; each killed term is the pure-immigration budget `b·∑aⁱ` (the `Φ(c₀)=0` collapse of
`phase0_killed_window_unconditional`), which is monotone in the step; so the `(σ+1)`-fold sum
is at most `(t+1)·(b·∑_{i<t}aⁱ)`.  Hypothesis surface: `Phase0Initial n c₀` + arithmetic. -/
theorem gap2_reachability_target_discharged (s : ℝ) (hs : 0 ≤ s) (n : ℕ) (hn2 : 2 ≤ n)
    (t : ℕ) (c₀ : Config (AgentState L K))
    (hinit : Phase0Initial (L := L) (K := K) n c₀) :
    Gap2_reachability_target (L := L) (K := K) s t c₀
      ((t + 1 : ℕ)
        * (ENNReal.ofReal (Real.exp (-(s * (50 * (L + 1) : ℕ))))
            * ∑ i ∈ Finset.range t,
                ENNReal.ofReal (1 + 2 * (Real.exp s - 1) / (n : ℝ)) ^ i)) := by
  classical
  set a := ENNReal.ofReal (1 + 2 * (Real.exp s - 1) / (n : ℝ)) with ha
  set b := ENNReal.ofReal (Real.exp (-(s * (50 * (L + 1) : ℕ)))) with hb
  have hc₀G : c₀ ∈ phase0Gate (L := L) (K := K) n := phase0Initial_mem_phase0Gate hinit
  intro σ hσ
  have hσt : σ < t := Finset.mem_range.mp hσ
  -- the first-escape decomposition: real prefix ≤ ∑_{i≤σ} killed-threshold.
  refine le_trans (gap2_real_bad_le_killed_threshold_prefix s n σ c₀ hc₀G) ?_
  -- each killed-threshold term ≤ b·∑_{i<σ} aⁱ ≤ b·∑_{i<t} aⁱ (monotone).
  have hterm : ∀ i ∈ Finset.range (σ + 1),
      (GatedDrift.killK_now (NonuniformMajority L K).transitionKernel
            (phase0Gate (L := L) (K := K) n) ^ i) (some c₀)
          {o | (1 : ℝ≥0∞)
                ≤ GatedDrift.killΦ (clockCounterPotential (L := L) (K := K) s) o}
        ≤ b * ∑ j ∈ Finset.range t, a ^ j := by
    intro i hi
    have hit : i ≤ t := le_of_lt (lt_of_le_of_lt (Nat.lt_succ_iff.mp (Finset.mem_range.mp hi)) hσt)
    refine le_trans (phase0_killed_window_unconditional s hs n hn2 i c₀ hinit) ?_
    exact killed_immigration_budget_mono a b hit
  refine le_trans (Finset.sum_le_sum hterm) ?_
  rw [Finset.sum_const, Finset.card_range, nsmul_eq_mul]
  -- (σ+1)·budget ≤ (t+1)·budget since σ + 1 ≤ t + 1.
  have hcast : ((σ + 1 : ℕ) : ℝ≥0∞) ≤ ((t + 1 : ℕ) : ℝ≥0∞) := by
    exact_mod_cast Nat.succ_le_succ (le_of_lt hσt)
  gcongr

/-! ## Stage 4 — the capstone: the UNCONDITIONAL real-chain Phase-0 window.

Feeding the discharged `Gap2_reachability_target` into the campaign's conditional close
`gap2_allPhase0_window_whp_of_reachability` removes its `hreach` hypothesis entirely.  The
result is the genuinely UNCONDITIONAL real-chain Phase-0 window: hypothesis surface
`Phase0Initial n c₀` + arithmetic ONLY.  This CLOSES Gap-2. -/

/-- **GAP-2 CLOSED — the UNCONDITIONAL real-chain Phase-0 window.**

From the balanced Phase-0 start `Phase0Initial n c₀` (and `2 ≤ n`), the real Doty chain's
probability of leaving `allPhase0` within `t` steps is bounded by an EXPLICIT
pure-immigration budget, with NO reachability/maintenance hypothesis:

  `(K^t) c₀ {¬ allPhase0} ≤ t · (t+1) · b · ∑_{i<t} aⁱ`,
  `a = ofReal(1 + 2(eˢ−1)/n)`,  `b = ofReal(e^{−s·50(L+1)})`.

The residual `Gap2_reachability_target` the campaign isolated is DISCHARGED
(`gap2_reachability_target_discharged`) via the first-escape decomposition: the real
clock-zero prefix masses are a finite sum of KILLED (surviving-trajectory) threshold masses,
each the clean decaying immigration budget — NOT the non-contracting REAL self-reference the
killed engine's `escape_le_threshold_prefix` produced.  Hypothesis surface: `Phase0Initial
n c₀` + arithmetic (`0 ≤ s`, `2 ≤ n`).  This is the campaign's Phase-0 Gap-2 headline. -/
theorem allPhase0_window_unconditional (s : ℝ) (hs : 0 ≤ s) (n : ℕ) (hn2 : 2 ≤ n)
    (t : ℕ) (c₀ : Config (AgentState L K))
    (hinit : Phase0Initial (L := L) (K := K) n c₀) :
    ((NonuniformMajority L K).transitionKernel ^ t) c₀
        {c | ¬ allPhase0 (L := L) (K := K) c}
      ≤ (t : ℝ≥0∞)
          * ((t + 1 : ℕ)
              * (ENNReal.ofReal (Real.exp (-(s * (50 * (L + 1) : ℕ))))
                  * ∑ i ∈ Finset.range t,
                      ENNReal.ofReal (1 + 2 * (Real.exp s - 1) / (n : ℝ)) ^ i)) := by
  classical
  have h0 : allPhase0 (L := L) (K := K) c₀ := fun a ha => (hinit.2 a ha).1
  exact gap2_allPhase0_window_whp_of_reachability s t c₀ h0 _
    (gap2_reachability_target_discharged s hs n hn2 t c₀ hinit)

end Phase0Window

end ExactMajority
