#!/usr/bin/env bash
# install-hooks.sh — install Ripple's git post-commit hook into the parent
# workspace repository. Safe to re-run; idempotent.
#
# Usage:
#   projects/Ripple/scripts/install-hooks.sh
#
# What it does:
#   - Resolves the git repo root (the workspace, not projects/Ripple — Ripple
#     is a subdirectory of the workspace repo, not its own repo).
#   - Writes .git/hooks/post-commit that invokes scripts/worklog-append.sh
#     whenever the latest commit touches projects/Ripple/.
#   - Marks the hook executable.
#
# The hook itself is NOT checked in (.git/ is local per clone), so after every
# fresh clone run this script once.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RIPPLE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_ROOT="$(git -C "${RIPPLE_DIR}" rev-parse --show-toplevel)"
HOOK_PATH="${REPO_ROOT}/.git/hooks/post-commit"

cat > "${HOOK_PATH}" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by projects/Ripple/scripts/install-hooks.sh — do not edit by hand.
# Appends the just-made commit to projects/Ripple/WORK_LOG.md if it touched
# Ripple Lean files.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
WORKLOG_SCRIPT="${REPO_ROOT}/projects/Ripple/scripts/worklog-append.sh"

# Only fire if the commit touches projects/Ripple/.
if git diff-tree --no-commit-id --name-only -r HEAD | grep -q '^projects/Ripple/'; then
  if [ -x "${WORKLOG_SCRIPT}" ]; then
    "${WORKLOG_SCRIPT}" HEAD || true
  fi
fi
HOOK

chmod +x "${HOOK_PATH}"
echo "Installed post-commit hook at: ${HOOK_PATH}"
