#!/usr/bin/env bash
# worklog-append.sh — append a single commit's metadata to projects/Ripple/WORK_LOG.md
#
# Usage:
#   scripts/worklog-append.sh                  # append HEAD
#   scripts/worklog-append.sh <commit-ish>     # append a specific commit
#
# Idempotent: if the commit's short hash is already present in WORK_LOG.md, exit 0.
# Skips commits that do not touch projects/Ripple/Ripple/**/*.lean.
#
# Invoked both by the git post-commit hook and manually (for backfill).

set -euo pipefail

# -- Locate workspace git root and worklog file -------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RIPPLE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"            # projects/Ripple
REPO_ROOT="$(git -C "${RIPPLE_DIR}" rev-parse --show-toplevel)"
WORKLOG="${RIPPLE_DIR}/WORK_LOG.md"

# Path prefix of Ripple Lean files relative to REPO_ROOT.
LEAN_PATHSPEC="projects/Ripple/Ripple"

COMMIT="${1:-HEAD}"

# -- Resolve commit metadata ---------------------------------------------------
FULL_HASH="$(git -C "${REPO_ROOT}" rev-parse --verify "${COMMIT}^{commit}" 2>/dev/null || true)"
if [ -z "${FULL_HASH}" ]; then
  echo "worklog-append: cannot resolve commit '${COMMIT}'" >&2
  exit 1
fi

SHORT_HASH="$(git -C "${REPO_ROOT}" rev-parse --short "${FULL_HASH}")"
SUBJECT="$(git -C "${REPO_ROOT}" log -1 --pretty=format:'%s' "${FULL_HASH}")"
UNIX_TS="$(git -C "${REPO_ROOT}" log -1 --pretty=format:'%at' "${FULL_HASH}")"

# Chicago-local time via `date -r` (BSD/macOS) with fallback to GNU `date -d`.
if date -r "${UNIX_TS}" +%Y >/dev/null 2>&1; then
  TS_CHICAGO="$(TZ=America/Chicago date -r "${UNIX_TS}" '+%Y-%m-%d %H:%M')"
else
  TS_CHICAGO="$(TZ=America/Chicago date -d "@${UNIX_TS}" '+%Y-%m-%d %H:%M')"
fi

# Branch containing the commit. For HEAD commits use the current branch name;
# for historical commits fall back to the first branch that contains it, else "-".
CURRENT_BRANCH="$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '-')"
HEAD_HASH="$(git -C "${REPO_ROOT}" rev-parse HEAD)"
if [ "${FULL_HASH}" = "${HEAD_HASH}" ] && [ "${CURRENT_BRANCH}" != "HEAD" ]; then
  BRANCH="${CURRENT_BRANCH}"
else
  BRANCH="$(git -C "${REPO_ROOT}" branch --contains "${FULL_HASH}" --format='%(refname:short)' 2>/dev/null \
              | grep -v '^(HEAD' | head -n1 || true)"
  [ -z "${BRANCH}" ] && BRANCH='-'
fi

# -- Compute Lean-file line delta ---------------------------------------------
# numstat: <added>\t<deleted>\t<path>. Sum added+deleted over Lean files under
# projects/Ripple/Ripple/. Skip commits with zero Lean churn.
LEAN_STATS="$(git -C "${REPO_ROOT}" show --numstat --format= "${FULL_HASH}" -- \
                "${LEAN_PATHSPEC}/*.lean" "${LEAN_PATHSPEC}/**/*.lean" 2>/dev/null || true)"

if [ -z "${LEAN_STATS}" ]; then
  # No Lean files touched — skip silently. (Exit 0 so post-commit hook is quiet.)
  exit 0
fi

DELTA="$(printf '%s\n' "${LEAN_STATS}" | awk '
  BEGIN { add = 0; del = 0 }
  $1 ~ /^[0-9]+$/ && $2 ~ /^[0-9]+$/ { add += $1; del += $2 }
  END { printf "%+d", (add - del) }
')"

# Alternative view: total touched lines (added + deleted). We use signed delta
# in the log line (matches the spec example "+31 lines").
# -- Ensure WORK_LOG.md exists -------------------------------------------------
if [ ! -f "${WORKLOG}" ]; then
  cat > "${WORKLOG}" <<'HEADER'
# Ripple — Work Log

Append-only log of proof progress. Every row = one git commit touching Lean code.
Format: `YYYY-MM-DD HH:MM | commit | branch | + lemma_name (line Δ)` — newest first.

Generated by scripts/worklog-append.sh (post-commit hook + manual backfill).

---
HEADER
fi

# -- Idempotency: bail if this commit is already logged -----------------------
if grep -qE "\\| ${SHORT_HASH} \\|" "${WORKLOG}" 2>/dev/null; then
  exit 0
fi

# -- Build log line ------------------------------------------------------------
LINE="${TS_CHICAGO} | ${SHORT_HASH} | ${BRANCH} | ${SUBJECT} | ${DELTA} lines"

# -- Prepend right after the "---" header separator ---------------------------
# Insert the line immediately after the first line matching exactly "---".
# If the line after the separator is blank we keep that blank line, then the
# new entry — so the newest entry is always on top of the existing list.
# Use awk -> temp file -> mv (portable; `sed -i` differs on BSD vs GNU).
TMP="$(mktemp "${WORKLOG}.XXXXXX")"
awk -v line="${LINE}" '
  BEGIN { inserted = 0; seen_sep = 0 }
  {
    if (!inserted && seen_sep) {
      # First line after the separator. If it is blank, print it first, then
      # our new entry, then continue as normal. Otherwise insert our entry
      # ahead of it.
      if ($0 == "") {
        print
        print line
      } else {
        print line
        print
      }
      inserted = 1
      next
    }
    print
    if (!inserted && $0 == "---") { seen_sep = 1 }
  }
  END {
    if (!inserted) {
      # No separator found, or separator was last line — append at end.
      if (seen_sep) { print line } else { print line }
    }
  }
' "${WORKLOG}" > "${TMP}"
mv "${TMP}" "${WORKLOG}"
